spring.datasource.url=jdbc:postgresql://postgres.mau.se:55432/
spring.datasource.username=ar9120
spring.datasource.password=61nlrve5
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect